---
  - name: Destroy F5 Clones
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ vm_hostname }}{{ ova_builds_var.tmpl_name }}-{{ item }}"
      state: absent
    delegate_to: localhost
    with_sequence: "start=1 count={{ ova_builds_var.build_count }} format=%.3d"

