---
# tasks install Declaritive Onboarding Latest
  
 - name: Get latest AS3 RPM name
   ansible.builtin.shell: curl -s -D - {{as3_uri}} | grep -E noarch.rpm | head -1 | cut -d "/" -f 7 | cut -d "=" -f 1 |  cut -d "\"" -f 1
   register: as3_output
   run_once: true

 - ansible.builtin.set_fact:
    as3_release: "{{as3_output.stdout_lines[0]}}"
   run_once: true

 - name: Get latest AS3 RPM version
   ansible.builtin.shell: curl -s -D - {{as3_uri}} | grep -E noarch.rpm | head -1 | cut -d "/" -f 6 
   register: as3_output
   run_once: true

 - ansible.builtin.set_fact:
    as3_release_tag: "{{as3_output.stdout_lines[0]}}"
   run_once: true

 - name: Grab AS3 RPM from github
   ansible.builtin.get_url:
    url: "{{as3_uri}}/download/{{as3_release_tag}}/{{as3_release}}?raw=true"
    dest: "~/"
    validate_certs: false
   run_once: true
   register: file_get
   retries: 10
   until: file_get is not failed

 - name: Grab the AS3 version from the home directory
   ansible.builtin.shell: ls -Art ~/f5-appsvcs-*.rpm | tail -n 1 | rev | cut -d/ -f 1 | rev
   register: ls_output
   run_once: true

 - ansible.builtin.set_fact:
    as3_rpm: "{{ls_output.stdout}}"
   run_once: true

 - name: Install AS3
   f5networks.f5_modules.bigip_lx_package:
    package: "~/{{as3_rpm}}"
    provider: "{{ provider }}"
   register: install_as3
   delegate_to: localhost
   retries: 10
   until: install_as3 is not failed