---

 - name: Wait for BIG-IP to be ready
   f5networks.f5_modules.bigip_wait:
     delay: 5
     provider: "{{provider}}"
   delegate_to: localhost

 - name: Configure F5 via DO
   ansible.builtin.uri:
     url: "https://{{ ansible_host }}:{{f5_admin_port}}/mgmt/shared/declarative-onboarding/declare"
     method: POST
     body: "{{ lookup('template','do_configure.j2', split_lines=False) }}"
     status_code: 202
     timeout: 300
     body_format: json
     force_basic_auth: true
     user: "{{ f5_user }}"
     password: "{{ f5_pass }}"
     validate_certs: false
   delegate_to: localhost
   register: do_result

 - name: Wait for DO Task to complete
   ansible.builtin.uri:
     url: "https://{{ ansible_host }}:{{f5_admin_port}}/mgmt/shared/declarative-onboarding/task/{{ do_result.json.id }}"
     method: GET
     return_content: true
     status_code: 200
     force_basic_auth: true
     user: "{{ f5_user }}"
     password: "{{ f5_pass }}"
     validate_certs: false
   register: atc_DO_status
   until: atc_DO_status is success
   retries: 30
   delay: 30
   delegate_to: localhost